

name: Deployment LP to AP YFSI SERVER

on:
  push:
    branches: dev-for-ap
jobs:

  Deployment:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/dev-for-ap'
        env:
          PRIVATE_KEY: ${{ secrets.IMG_AP_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.IMG_AP_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.IMG_AP_HOSTNAME }} '
            cd /var/www/html/LP &&
            sudo git fetch origin &&
            sudo git checkout dev-for-ap &&
            sudo git pull origin dev-for-ap '
 

            

  
